---
booktitle: Neural Information Processing Systems (NIPS) Mini-Symposium on Causality
  in Time Series
month: 0
publisher: JMLR Workshop and Conference Proceedings
volume: 12
year: '2009'
start: 2009-12-10
end: 2009-12-10
published: 2011-03-03
shortname: Causality in Time Series
layout: proceedings
series: Proceedings of Machine Learning Research
id: PopescuCausality09
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
sections: 
editor:
- given: Florin
  family: Popescu
- given: Isabelle
  family: Guyon
description: |
  Neural Information Processing Systems (NIPS) Mini-Symposium on Causality in Time Series
    Held in Vancouver, Canada on 10 December 2009

  Published as Volume 12 by the Proceedings of Machine Learning Research on 03 March 2011.

  Volume Edited by:
    Florin Popescu
    Isabelle Guyon

  Series Editors:
    Neil D. Lawrence
url: http://proceedings.mlr.press
baseurl: "/v12"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v12
email: ''
conference:
  name: Neural Information Processing Systems (NIPS) Mini-Symposium on Causality in
    Time Series
  url: 
  location: Vancouver, Canada
  dates:
  - 2009-12-10
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v12.bib
